version: '3.6'

networks:
  mail-network:
    driver: bridge

services:
  mail-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - POSTGRES_URL=mail-postgres
      - REDIS_URL=mail-redis
    depends_on:
      - mail-postgres
      - mail-redis
    networks:
      - mail-network
    links:
      - mail-postgres
      - mail-redis
    container_name: mail-api
    command: yarn dev
    ports:
      - 3333:3333

  mail-queue:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - POSTGRES_URL=mail-postgres
      - REDIS_URL=mail-redis
    depends_on:
      - mail-postgres
      - mail-redis
    networks:
      - mail-network
    links:
      - mail-postgres
      - mail-redis
    container_name: mail-queue
    command: yarn queue

  mail-postgres:
    image: postgres
    container_name: mail-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /tmp/postgres:/bitnami
    networks:
      - mail-network

  mail-redis:
    image: bitnami/redis:latest
    container_name: mail-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - /tmp/redis:/bitnami/redis/data
    networks:
      - mail-network
